### ISSUE TITLE
Epic: replace JQuery widgets by VueJS components

### ISSUE THREAD

**Issue by vinyll** [opendatateam/udata#526]
The following JS widgets should be removed and replaced by their VueJS components:

- [ ] Integrate-Btn: check usage in _territoire_ project prior to refactor this
- [ ] issues-btn: in progress
- [ ] featured: to do
- [ ] share-btn: done, delete widget
- [ ] follow-btn: done, delete widget 
- [ ] ellipsis: to do
- [ ] popover: Vuejs exists, insert directive where old widget is still used (see plugin / tooltip)
- [ ] datarange-picker: use from vuestrap

To do last:
- [ ] modal: delete widget, clear usage in admin

Most of these widgets are located on _/js/widgets_ and may be migrated to _/js/components_

**Comment by vinyll** [comment]
_featured_: https://github.com/opendatateam/udata/pull/527

**Comment by jdesboeufs** [comment]
Share and Follow seem to have been migrated. Cc @vinyll
